// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://koofszunbjyzhnhzpvct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtvb2ZzenVuYmp5emhuaHpwdmN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzc3MDAsImV4cCI6MjA3MDg1MzcwMH0.JFaLR4WnAUqV7_U0Hgx9z3R57ZVVDgLi1WGaOcEu2Pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});